version: '2'
services:
  server:
    environment:
      - 'PGHOST=postgres'
      - 'PGPORT=5432'
      - 'PORT=8080'
    image: 'arnarfs15/reference-tictactoe'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
