version: '2'
services:
  server:
    environment:
      - 'PGHOST=NODE_ENV'                    #needs to be fixed
      - 'PGPORT=5432'                        #sets the PGport to 5432 for the db
      - 'PORT=80'                            #port 80 for AWS
    image: 'arnarfs15/reference-tictactoe'   #sets the image being worked on, $GIT_COMMIT needs to be added later
    ports:
      - '8080:8080'                          #Port 8080
      - '80:80'                              #Port 80, AWS
    depends_on:
      - 'postgres'                           #the server needs postgres to work
  postgres:
    image: 'postgres'                        #declares that the image used is postgres
    environment:
      - POSTGRES_USER=postgres               #Sets user as postgres
      - POSTGRES_PASSWORD=mysecretpassword   #sets the password to mysecretpassword
    ports:
      - '5432:5432'                          #the postgres port 5432
