version: '2'
services:
  server:
    environment:
      - 'PGHOST=NODE_ENV'
      - 'PGPORT=5432'
      - 'PORT=3000'
    image: 'arnarfs15/reference-tictactoe'
    ports:
      - '8080:8080'
      - '3000:3000'
    depends_on:
      - 'postgres'
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
